### ISSUE TITLE
Cannot upload binary using `files.upload` facet

### ISSUE THREAD

**Issue by pveyes** [slackhq/node-slack-client#103]
Version: 2.0.0-beta2

Cannot send binary file to upload via `files.upload`. I tried using Buffer and ReadStream (via `fs.createReadStream`) but no luck. 

Here's my code (more or less)
```js
var api = new WebClient(token);
var opts = {
  filename: 'test.jpg',
  file: fs.createReadStream('test.jpg')
};
api.files.upload(opts, function (err, res) {
  console.log(res);
  // { ok: false, error: 'no_file_data' }
});
```

If I call api directly using `request` module, I can sent them (using `r.form()`)
```js
var r = request.post('https://slack.com/api/files.upload', function (err, res, body) {
  // this works
});

var form = r.form();
form.append(token, token);
form.append('filename', 'test.jpg');
form.append(file, fs.createReadStream('test.jpg');
```

**Comment by l12s** [comment]
Thanks, will check this out today

**Comment by l12s** [comment]
Sorry for the delay on this, I got busy and then was on vacation for a week.

I believe the above PR fixes this.

**Comment by webus** [comment]
It's not working still. I tried to send a picture in chat but Slack sees it as a text and it shows as text.
```javascript
let WebClient = require("@slack/client").WebClient;
let web = new WebClient(accessToken);
let opts = {
    content: fs.readFileSync(imageFilePath),
    filename: 'image.jpg',
    title: 'image.jpg',
    channels: 'demo'
};
web.files.upload(msg.photo.caption, opts, (err, res) => {
    if (err) {
        // no errors here
    } else {
        // here i receive the data about the uploaded file, and there it is listed as plain text
    }
});
```
Of course, I found the solution on the advice of @pveyes.

**Comment by pveyes** [comment]
@webus shouldn't you use `file` instead of `content` in opts?

**Comment by jsarafajr** [comment]
Getting `Error: no_file_data` while uploading Buffer object with files.upload. Seems that this is connected with issues above.

```js
// doesn't work (see trace log below)
const image = fs.readFileSync('image.png');
await bot.files.upload('image.png', {
  file: image
});

// text buffer doesn't work too
await bot.files.upload('text.txt', {
  file: new Buffer('hello world');
});

// uploads image as Plain Text (incorrect)
await bot.files.upload('image.png', {
  content: image
});

// works well with streams
const imageStream = fs.createReadStream
await bot.files.upload('image.png', {
  file: imageStream
});
```

```bash
2016-12-27T13:58:29.415Z - error:  Error: no_file_data
     at handleHttpResponse (/bot/node_modules/@slack/client/lib/clients/transports/call-transport.js:105:17)
     at handleTransportResponse (/bot/node_modules/@slack/client/lib/clients/transports/call-transport.js:155:19)
     at apply (/bot/node_modules/lodash/lodash.js:499:17)
     at wrapper (/bot/node_modules/lodash/lodash.js:5356:16)
     at Request.handleRequestTranportRes (/bot/node_modules/@slack/client/lib/clients/transports/request.js:20:5)
     at apply (/bot/node_modules/lodash/lodash.js:499:17)
     at Request.wrapper [as _callback] (/bot/node_modules/lodash/lodash.js:5356:16)
     at Request.self.callback (/bot/node_modules/request/request.js:186:22)
...
```

**Comment by GyozaGuy** [comment]
I can also verify that `no_file_data` is returned when using `readFileSync`, but using `createReadStream` does work.

**Comment by clavin** [comment]
See [my answer to #307](https://github.com/slackapi/node-slack-sdk/issues/307#issuecomment-289231737) for uploading a buffer via the `files.upload` facet.
