### ISSUE TITLE
files.upload fails and logs an error

### ISSUE THREAD

**Issue by Starfox64** [slackhq/node-slack-client#212]
I have been trying to upload snippets using the API but an error is printed.

```javascript
var SlackClient = require('@slack/client');
var WebClient = new SlackClient.WebClient('[[REDACTED]]');

WebClient.files.upload('hello.txt', {
	content: 'Hello World'
}, function(err, data) {
	console.log(err, data);
});
```

```
error:  TypeError: apiCb is not a function
    at handleHttpResponse (C:\Users\Starfox64\Documents\GitHub\supinbot\node_modules\@slack\client\lib\clients\transports\call-transport.js:103:5)
    at handleTransportResponse (C:\Users\Starfox64\Documents\GitHub\supinbot\node_modules\@slack\client\lib\clients\transports\call-transport.js:140:19)
    at wrapper (C:\Users\Starfox64\Documents\GitHub\supinbot\node_modules\@slack\client\node_modules\lodash\index.js:3592:19)
    at Request.handleRequestTranportRes (C:\Users\Starfox64\Documents\GitHub\supinbot\node_modules\@slack\client\lib\clients\transports\request.js:20:5)
    at Request.wrapper [as _callback] (C:\Users\Starfox64\Documents\GitHub\supinbot\node_modules\@slack\client\node_modules\lodash\index.js:3592:19)
    at Request.self.callback (C:\Users\Starfox64\Documents\GitHub\supinbot\node_modules\request\request.js:198:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (C:\Users\Starfox64\Documents\GitHub\supinbot\node_modules\request\request.js:1035:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (C:\Users\Starfox64\Documents\GitHub\supinbot\node_modules\request\request.js:962:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (node.js:377:13)
```

**Comment by l12s** [comment]
which version of the client are you running?

**Comment by Starfox64** [comment]
Looks like npm did not update to 3.1.0 on my other computer, it was still running 2.1.0.

**Comment by yalelikeyale** [comment]
I just got this same error minutes after installing the client and running a basic request that i had tested via api.slack.com/methods/files.list/test?

**Comment by yalelikeyale** [comment]
var WebClient = require('@slack/client').WebClient;

var slack = new WebClient(token);

slack.files.list(token, file_id, function(err, info) {
   //err is set if there was an error 
   //otherwise info will be an object that contains the result of the call
   if (!err) {
       console.log(info.file.url_private_download);
   }
});
