### ISSUE TITLE
Error - please help

### ISSUE THREAD

**Issue by Joxxorz** [slackhq/node-slack-client#76]
I'm getting this error code, what can I do? Sorry, I'm very new to all this grunt stuff.

Error: Cannot find module 'grunt-legacy-log-utils'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Volumes/webserver/jock/zinvite/node_modules/grunt/node_modules/grunt-legacy-log/index.js:25:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

Thank you.

**Comment by CaptainPalapa** [comment]
Jox...what was your solution?
