### ISSUE TITLE
On user leaving channel, slack errors

### ISSUE THREAD

**Issue by thomassross** [slackhq/node-slack-client#89]
node_modules/slack-client/src/channel.js:78
            index = this.members.indexOf(message.user);
                                ^

    TypeError: Cannot read property 'indexOf' of undefined
        at Channel.addMessage (node_modules/slack-client/src/channel.js:78:29)
        at Client.onMessage (node_modules/slack-client/src/client.js:486:26)
        at WebSocket.<anonymous> (node_modules/slack-client/src/client.js:140:24)
        at emitTwo (events.js:87:13)
        at WebSocket.emit (events.js:172:7)
        at Receiver.ontext (node_modules/slack-client/node_modules/ws/lib/WebSocket.js:816:10)
        at node_modules/slack-client/node_modules/ws/lib/Receiver.js:477:18
        at Receiver.applyExtensions (node_modules/slack-client/node_modules/ws/lib/Receiver.js:364:5)
        at node_modules/slack-client/node_modules/ws/lib/Receiver.js:466:14
        at Receiver.flush (node_modules/slack-client/node_modules/ws/lib/Receiver.js:340:3)

**Comment by l12s** [comment]
Ok, first off, I apologize for how long it's taken us to resolve this issue.

I just pushed the 2.0.0 release for this library, which is a ground up refactor with the aim of building a lib that both Slack and our external contributors can easily work with and improve.

I'm pretty certain that will resolve the issue you ran into. I'm fairly sure that the error you saw was due to the `Channel` object being constructed from a JSON object without the `members` property. The new client [updates model objects](https://github.com/slackhq/node-slack-client/blob/master/lib/models/model.js#L41) when messages are received, rather than replacing them, so that the `members` property that was received during `rtm.start` will be retained. That means that the [leave handler](https://github.com/slackhq/node-slack-client/blob/master/lib/data-store/message-handlers/channels.js#L39) shouldn't error in this way going forwards.
